### ISSUE TITLE
stream get content

### ISSUE THREAD

**Issue by mts88** [mts88/mongogrid#3]
function getFileContent obtain null on 
return stream_get_contents( $this->getFileStreamById( $source ) );

**Comment by kudaibergenoff** [comment]
function storeFile produces an error "Undefined variable: file_id"/ Why?

**Comment by mts88** [comment]
Can you post your code?

**Comment by kudaibergenoff** [comment]
I connected this package to the Laravel 5,7 and configured it as described but it gives out a bug "Undefined variable: file_id"

this is my controller:
`namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Mts88\MongoGrid\Facades\MongoGrid;
use Illuminate\Support\Facades\Storage;

class TestController extends Controller
{
    public function index(){
        $fileName = 'image.png';
        $fileContent = Storage::disk('local')->get('image.png');
        $objectId = MongoGrid::storeFile($fileContent, $fileName); 
    }
}`

` 'db_config' => [
        'host'     => env('DB_HOST', 'localhost'),
        'port'     => env('DB_PORT', 27017),
        'database' => env('DB_DATABASE'),
        'username' => env('DB_USERNAME'),
        'password' => env('DB_PASSWORD'),
        'options'  => [
            'database' => 'admin' // sets the authentication database required by mongo 3
        ]
    ],`

**Comment by kudaibergenoff** [comment]
sorry my bad english

**Comment by mts88** [comment]
What's your log about that? 
"Undefined variable: file_id" means that function storeFile can't read data from DB so can't return file_id.
In your log must be an Exception before "Undefined variable: file_id". 
Can you check?

PS: this library is not tested with Laravel 5.7. Max version tested is 5.6

**Comment by kudaibergenoff** [comment]
here is the function:
`public function storeFile( string $fileSource, string $fileName, array $metadata = [] ) {

        $f = finfo_open();
        $mime_type = finfo_buffer($f, $fileSource, FILEINFO_MIME_TYPE);

        $options = array(
            'contentType'	=>	 $mime_type,
            'metadata'      =>   [
            ]
        );

        if( $this->config['add_meta'] ) {
            $options['metadata'] = array_merge($options['metadata'], array(
                'created_at'    =>  new \MongoDB\BSON\UTCDateTime( Carbon::now() ),
                'updated_at'    =>  new \MongoDB\BSON\UTCDateTime( Carbon::now() ),
                'uuid'          =>  Uuid::uuid1()->toString(),
                'downloads'     =>  0
            ), $metadata);
        }

        try {
            $this->storage->put($fileName, $fileSource);
            $path = $this->path_prefix . $fileName;

            $file = fopen( $path , 'rb');

            $file_id = $this->bucket->uploadFromStream( $fileName, $file, $options);

            unlink($path);
        } catch (\MongoDB\Exception\InvalidArgumentException $e) {
            \Log::error("InvalidArgumentException: " . $e->getMessage());
        } catch (\MongoDB\Driver\Exception\RuntimeException $e) {
            \Log::error("RuntimeException: " . $e->getMessage());
        }

		return $file_id;
	}`

**Comment by mts88** [comment]
I need Log about the error.
You error means that this part
`   
try {
        $this->storage->put($fileName, $fileSource);
        $path = $this->path_prefix . $fileName;

        $file = fopen( $path , 'rb');

        $file_id = $this->bucket->uploadFromStream( $fileName, $file, $options);

        unlink($path);
    } catch (\MongoDB\Exception\InvalidArgumentException $e) {
        \Log::error("InvalidArgumentException: " . $e->getMessage());
    } catch (\MongoDB\Driver\Exception\RuntimeException $e) {
        \Log::error("RuntimeException: " . $e->getMessage());
    }`

cannot read from Db, so there is in log file an exception InvalidArgumentException or RuntimeException. Check it, please.

**Comment by kudaibergenoff** [comment]
sorry for dullness, I'm just a beginner, I'll send you a screen

![log](https://user-images.githubusercontent.com/14032990/45088746-c0bb2380-b12b-11e8-89e5-e25ab8572441.PNG)

**Comment by kudaibergenoff** [comment]
Here such error I receive

**Comment by mts88** [comment]
Open file in storage/logs/laravel.log and search the error inside. Or if you can, attach the file in reply.

**Comment by kudaibergenoff** [comment]
[laravel.log](https://github.com/mts88/mongogrid/files/2352443/laravel.log)
Log file

**Comment by mts88** [comment]
Found it: if you check the log file there is an RuntimeException:
`[2018-09-05 09:53:36] local.ERROR: RuntimeException: Authentication failed.  
[2018-09-05 09:53:36] local.ERROR: Undefined variable: file_id {"exception":"[object] (ErrorException(code: 0): Undefined variable: file_id at C:\\WebServer\\OSPanel\\domains\\armadatest1.dev\\vendor\\mts88\\mongogrid\\src\\Services\\MongoGrid.php:130)
[stacktrace]
#0 C:\\WebServer\\OSPanel\\domains\\armadatest1.dev\\vendor\\mts88\\mongogrid\\src\\Services\\MongoGrid.php(130): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined varia...', 'C:\\\\WebServer\\\\OS...', 130, Array)
#1 C:\\WebServer\\OSPanel\\domains\\armadatest1.dev\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php(223): Mts88\\MongoGrid\\Services\\MongoGrid->storeFile('\\x89PNG\
\`

The problem is the Authentication. Check your connection.

For the future: open a new issue. Don't ask in others. Thanks.

**Comment by kudaibergenoff** [comment]
ok now check. Thank's

**Comment by kudaibergenoff** [comment]
how do I connect to the database correctly?

**Comment by mts88** [comment]
Check your username and password of MongoDB, and the database authentication. For more details check [MongoDB Docs](https://docs.mongodb.com/?_ga=2.227818971.739767052.1536146060-594543909.1527862879).

**Comment by kudaibergenoff** [comment]
I do not have a username and password yet

**Comment by mts88** [comment]
So you can't connect. This is a library for Laravel to use GridFS of MongoDB, I think you should learn more about Mongo and the use of a DB.

**Comment by kudaibergenoff** [comment]
my .env file 
`DB_CONNECTION=mongodb
DB_HOST=127.0.0.1
DB_PORT=27017
DB_DATABASE=gridfs
DB_USERNAME=
DB_PASSWORD=`


database.php
`'connections' => [

        'sqlite' => [
            'driver' => 'sqlite',
            'database' => env('DB_DATABASE', database_path('database.sqlite')),
            'prefix' => '',
        ],
        'mongodb' => [
            'driver'   => 'mongodb',
            'host'     => env('DB_HOST', '127.0.0.1'),
            'port'     => env('DB_PORT', 27017),
            'database' => env('DB_DATABASE'),
            'username' => env('DB_USERNAME'),
            'password' => env('DB_PASSWORD')    
        ],`

gridfs.php

`'db_config' => [
        'host'     => env('DB_HOST', 'localhost'),
        'port'     => env('DB_PORT', 27017),
        'database' => env('DB_DATABASE'),
        'username' => env('DB_USERNAME'),
        'password' => env('DB_PASSWORD'),
        'options'  => [
            'database' => 'admin' // sets the authentication database required by mongo 3
        ]
    ],`

**Comment by kudaibergenoff** [comment]
I connected using the native php-mongodb library

**Comment by mts88** [comment]
The library use his own connection manager, so you have to insert username and password. If you don't have, create it on mongo. The library can't use your connection.

**Comment by kudaibergenoff** [comment]
ok .thank you
