### ISSUE TITLE
[Feature Request] Get DB config from config/database.php

### ISSUE THREAD

**Issue by msyahidin** [mts88/mongogrid#4]
Hi @mts88 , nice package

Trying to add it to my project, but while I read the config file, it has independent db config from Laravel Config database.
I expected like this
```
  'db_config' => ['mongodb']
```
array value from database connection list on database config file.

Thank You

**Comment by mts88** [comment]
@msyahidin  thank you for your request. I've choosed to separate the configuration for more scalable use, but it's a good request so I will implement soo the possibility to use both configurations (database.php or gridfs.php).

If you have other ideas o others missing features please ask.

See you soon.

**Comment by mts88** [comment]
Hi @msyahidin the requested feature is released in [version 1.1.0](https://github.com/mts88/mongogrid/tree/v1.1.0) #5 . 
Thank you for your suggest.
